### ISSUE TITLE
Ability to cancel a connection

### ISSUE THREAD

**Issue by jaythomas** [Paxa/postbird#105]
Attempting to open a bad connection, there is no way to cancel the connection attempt:

![Screenshot from 2020-02-14 17-51-19](https://user-images.githubusercontent.com/2344456/74574824-ea988c80-4f52-11ea-9930-a80365f87917.png)

To make matters worse, the default timeout seems to be around 120 seconds so you have to wait awhile if you made a mistake with your url. (Is there a way to change the connection timeout limit?)

**Comment by Paxa** [comment]
Implemented

**Comment by jaythomas** [comment]
Thank you! :tada:
