### ISSUE TITLE
The download  in progress is very slow and taking too long

### ISSUE THREAD

**Issue by maheshmnj** [Paxa/postbird#109]
I am trying to download the dmg file for mac and it is very slow here in India,
I  tried running speed test and It was around 70mbps for me and it works pretty well for other sites but incase of downloading this file its too slow
![image](https://user-images.githubusercontent.com/31410839/78868350-6a793980-7a60-11ea-97fb-7ca830924f81.png)

can you move them to some fast servers if possible or provide some alternate link that is suitable?Even a Google Drive /One Drive could help .

**Comment by Paxa** [comment]
Hi, sorry to hear about this, it happens to me too. I guess github is getting too popular...

For now you can try get from here https://postbird.paxa.kuber.host/
Thanks for suggestion with google drive, I will definitely do something like this for upcoming release
