### ISSUE TITLE
Unsupported frontend protocol when connecting to postgres@12.2

### ISSUE THREAD

**Issue by DiskImage** [Paxa/postbird#111]
Below is a screenshot of what happens when I try to view the info tab while connected to a postgres v12.2 db on macOS@10.14.6. The same issue occurs anytime I try to import a `.sql` file. I'm guessing the bundled utilities need a version bump or something?

![image](https://user-images.githubusercontent.com/1789383/80736362-a475b280-8ad7-11ea-865b-67bab4b3a993.png)

**Comment by Paxa** [comment]
Try latest builds, they come with binaries for postgres 13
https://postbird.paxa.kuber.host/
