### ISSUE TITLE
connection postgre

### ISSUE THREAD

**Issue by iamfelipy** [Paxa/postbird#112]
i can't connect to aws rdp using postbird.
Could you show me an example of connection standard and connection url?
[https://prnt.sc/saaqom](url)
https://prnt.sc/saardi

**Comment by Paxa** [comment]
If you talk about RDS (managed postgres by aws) then we need to enable remote access

https://www.percona.com/blog/2018/05/08/how-to-enable-amazon-rds-remote-access/

Or use ssh tunnel 

```
ssh name@123.12.34.56 -L 15432:127.0.0.1:5432 -N
                          ^ local port     ^ remote port
```

Then connect to 127.0.0.1 port 15432

**Comment by iamfelipy** [comment]
thanck you
