### ISSUE TITLE
Windows installer version 0.8.4 is not available for download

### ISSUE THREAD

**Issue by fahofmeister** [Paxa/postbird#114]
The link for the download is broken (error 404). Here is the link href as it is on the download section:
https://github.com/Paxa/postbird/releases/download/0.8.4/Postbird.Setup.0.8.4.exe

![image](https://user-images.githubusercontent.com/26206479/83337453-cb1f3880-a291-11ea-892f-fb4cb89efd49.png)

**Comment by mastazi** [comment]
Just in case anyone sees this: the correct link is the following 
https://github.com/Paxa/postbird/releases/download/0.8.4/Postbird-Setup-0.8.4.exe

**Comment by Paxa** [comment]
It's been fixed
