### ISSUE TITLE
CSV export?

### ISSUE THREAD

**Issue by scottlee120** [Paxa/postbird#12]
Hi - I love your work and prefer postbird to say PSequel (which is the other tool I left installed after trying at least a dozen). That said, I can't find any CSV export functions - is that somewhere in there or is it something not yet available?

**Comment by Paxa** [comment]
It is something not yet available. Would be nice to have

Do you want to export query result as CSV or table data or whole database?

Where do you think such should be placed?

**Comment by josegonzalez** [comment]
I think at minimum, we should be able to export the results of a query as any of the following:

- csv
- json
- sql

Exporting tables and databases is nice, but likely to happen more via CLI for large tables, so can probably be a "v2" thing.

The export buttons would be:

- On the action bar separating queries from results on the query sub-tab: ![https://cl.ly/0G1l2E2Q1U1o](https://cl.ly/0G1l2E2Q1U1o/Image%202017-05-26%20at%2010.48.29%20PM.png)
- On the bottom-right bar for tables: ![https://cl.ly/1v0B1X3B2G3w](https://cl.ly/1v0B1X3B2G3w/Image%202017-05-26%20at%2010.49.08%20PM.png)

**Comment by Paxa** [comment]
Thanks for comment, @josegonzalez.

Making SQL format can be hard, and for clipboard, I think just use tab-separated format, so it can be easily inserted to excel or google spreadsheets

**Comment by Paxa** [comment]
I added simple support for CSV export of query result, please try https://github.com/Paxa/postbird/releases/tag/0.7.0

**Comment by chrislawlor** [comment]
Just tried this out, it only exports the first 500 rows.

**Comment by Paxa** [comment]
This was fixed in latest release

**Comment by arichiardi** [comment]
Hi there, is there a way currently to re-import that csv that got exported? I saw a "import .sql" somewhere but not .csv...

**Comment by comtom** [comment]
> Hi there, is there a way currently to re-import that csv that got exported? I saw a "import .sql" somewhere but not .csv...

You can use postgres command, /copy or copy statement to do that. Currently postbird doesn't have the ability to import.
