### ISSUE TITLE
self signed certificate error when building yarn dist

### ISSUE THREAD

**Issue by geeknees** [Paxa/postbird#130]
There doesn't seem to be a release since 11/20/2019, but upstream seems to have solved a few issues. I have a build in hand to take advantage of it, but I'm getting a self signed certificate error on SSL connections. Am I missing some step in the build here?

<img width="261" alt="スクリーンショット 2021-05-19 20 13 45" src="https://user-images.githubusercontent.com/701242/118804668-f2767780-b8df-11eb-82df-430f8cf7bb39.png">

**Comment by Paxa** [comment]
Hi, that seems like error when connecting to server, do you get same error when connecting via psql ?

Probably should make SSL configurable, right now it will try to auto-detect SSL support on server

**Comment by Paxa** [comment]
For now to connect to server with self signed certificate need to use `rejectUnauthorized=false` in connection URL (added in recent commit)

If you have time, can you please try https://nightly.link/Paxa/postbird/workflows/build/master
