### ISSUE TITLE
pg_dump: error: server version: 14.0; pg_dump version: 12.0

### ISSUE THREAD

**Issue by adamzerner** [Paxa/postbird#140]
Hey guys, I am getting set up with postgres for the first time. I used https://postgresapp.com/ to start the server and it seems like all is good there. Then in Postbird, I used the following connection:

<img width="393" alt="Screenshot 2021-10-20 at 1 13 19 AM" src="https://user-images.githubusercontent.com/3144254/138054413-8e04954c-bbbf-4329-96a7-71669fda66ea.png"> 

It works when I click "Connect". I then created a new database called `calibration-training` (for a side project I am working on). Then I created a table called `Test`, added a column to that table called `name` (`varchar`), and added a single record with an `id` of `1` and a `name` of `first`. It looks like it worked.

<img width="975" alt="Screenshot 2021-10-20 at 1 15 57 AM" src="https://user-images.githubusercontent.com/3144254/138054888-1e24a76d-dbf8-4046-8658-97447806ef62.png">

But then when I tried to retrieve the record via my Node.js app, I got an error. So I started investigating, and in doing so I clicked the "Info" tab and found this:

<img width="1440" alt="Screenshot 2021-10-20 at 1 17 19 AM" src="https://user-images.githubusercontent.com/3144254/138055078-5f5a0715-941e-4a6a-ae45-abce00dbb3b9.png">

So I'm getting this error:

```
Loading...Error happen while running pg_dump:
pg_dump: error: server version: 14.0; pg_dump version: 12.0
pg_dump: error: aborting because of server version mismatch
```

This is where I am totally lost. When I go to the command line, it looks like I don't have that executable, so I don't know how to proceed.

```
code/calibration-training-api [master●] » pg_dump
zsh: command not found: pg_dump
```

Any tips?

**Comment by anthonydb** [comment]
Hi, 
I don't work on this project but noticed your note. When you set up Postgress.app, did you set up the command line tools using step 3 on the main page? https://postgresapp.com/

**Comment by adamzerner** [comment]
Nevermind, I decided to go with a different Postgres GUI instead.

**Comment by maticrivo** [comment]
@adamzerner I'm facing the same issue, what Postgres GUI are you using instead?
