### ISSUE TITLE
Feature request - Add dark theme

### ISSUE THREAD

**Issue by adam-718** [Paxa/postbird#144]
Hi Postbird team,
I would like very much to get a dark theme for the app.

I'm using Postbird 0.8.4 on Ubuntu 22.04LTS
Thanks very much for the great work you're doing 🙏
Adam

**Comment by comtom** [comment]
The app actually has a dark theme, just seems not is properly reading system preference in linux. We have an open MR to improve dark mode https://github.com/Paxa/postbird/pull/123 you're welcome to contribute as well

**Comment by MattKleinsmith** [comment]
@comtom Hi, any idea how to enable the dark theme on Windows?
