### ISSUE TITLE
Read-Only Mode

### ISSUE THREAD

**Issue by kanyukaaa** [Paxa/postbird#20]
It would be great to have the option to start a connection in read-only mode.

Currently, I call this command after connection, but it's easy to forget to do:
```sql
SET SESSION CHARACTERISTICS AS TRANSACTION READ ONLY; 
```
It may even be better to implement this not as a checkbox, but as a custom query that runs each time you connect.

**Comment by Paxa** [comment]
I think it's gonna be useful. Will try to add

**Comment by Paxa** [comment]
Implemented by https://github.com/Paxa/postbird/commit/2b9a6d467f433bcda1ec90d910221b78fa8be5e1
