### ISSUE TITLE
Space bar dismisses the "edit value" dialog

### ISSUE THREAD

**Issue by boblauer** [Paxa/postbird#24]
Ff you're in the "Edit Value" dialog and hit the space bar, the dialog is dismissed and the record is not saved.  This makes adding a space to a text value impossible.

The issue is that `hasInput` is `false` on L172:

https://github.com/Paxa/postbird/blob/dbe4d12f3d2810bc263a2c994e5afaa1b4380fd4/lib/alertify.js#L170-L173

**Comment by Paxa** [comment]
Thank you for reporting. Will fix

**Comment by Paxa** [comment]
Fixed by https://github.com/Paxa/postbird/commit/d234a8de24c2b162b456c7f5a7490d4856bf57d7
