### ISSUE TITLE
Allow for piecemeal connection configuration OR uri

### ISSUE THREAD

**Issue by krainboltgreene** [Paxa/postbird#28]
Many postgres services have a uri you can use to make a connection. Allow users to paste this into a new connection.

**Comment by Paxa** [comment]
Good idea, will add it
Btw what is piecemeal connection?

**Comment by krainboltgreene** [comment]
Sorry, as in "in pieces", aka the current way.

**Comment by Paxa** [comment]
Implemented in 0.8
