### ISSUE TITLE
Install with homebrew

### ISSUE THREAD

**Issue by AnderScore** [Paxa/postbird#34]
Add postbird to Brew repository.

https://apple.stackexchange.com/questions/97065/how-do-i-write-a-homebrew-recipe

**Comment by Paxa** [comment]
Yes, surprisingly it's already there 😀 `brew cask info postbird`

**Comment by stepchud** [comment]
this needs an update, the latest version on homebrew is 0.7.1

**Comment by tzinmein** [comment]
I've submitted a [PR](https://github.com/Homebrew/homebrew-cask/commit/0d22cc7b72254037893f4b3f2dffe56c6a4b38ca) to homebrew-cask for 0.8.0

**Comment by Paxa** [comment]
Thank you
