### ISSUE TITLE
linux support

### ISSUE THREAD

**Issue by Naatan** [Paxa/postbird#35]
Seeing as this is Electron based why limit yourself to macOS? Linux still needs a good Postgres GUI client.

**Comment by Paxa** [comment]
I would really like it! But I rarely use linux with UI now, so it's hard for me to test

Last time I tried to run it on debian and I think it worked...  can you try to run it from git?

```
git clone https://github.com/Paxa/postbird.git
cd postbird
yarn
yarn run rebuild_ext # optional
yarn start
```

And how do you think UI should be?

**Comment by Naatan** [comment]
Seems to work without any serious issues:

![image](https://user-images.githubusercontent.com/278649/43589460-be515e8e-963c-11e8-81a5-9230c6346bb9.png)

It's functional though obviously looks a bit out of place on Linux. I think ideally what I'd like to see from the UI is for the menu to be hidden (put it in a burger menu or something) and the titlebar to match the theme.

That's all aesthetic nitpickery though; I would totally use it as is. I guess the only thing it REALLY needs is a Linux distribution.

**Comment by Paxa** [comment]
Cool, do you know how to pack for Linux? Make deb and rpm or we can also submit in some repository?

**Comment by Naatan** [comment]
I would just get a tar.gz out there with all the essentials (.application file, icon, compiled binaries, etc), leave it to others to create distro specific variations. If the demand is there the community will follow. Having spent some time researchin postgres GUI's for Linux I can definitely say this is the closest I've seen to something that helps me just "get shit done" (rather than hey - here's 893428 things postgres does, have fun finding the 1 thing you care about).

**Comment by ygorcanalli** [comment]
I think that @Naatan suggestion of make a tar.gz would be a nice start.

**Comment by alexanderadam** [comment]
@Paxa well, if building and running on Linux works without any issues: I guess you can change the repository description then. :wink:

**Comment by nmabhinandan** [comment]
You can use electron-packager

**Comment by 12Factor-mx** [comment]
sqlelectron is another option https://sqlectron.github.io/

**Comment by 12Factor-mx** [comment]
indeed sqlelectron works great for cockroachDB (not a Postgress) that is a DB that uses the Postgress communication protocol

**Comment by 12Factor-mx** [comment]
By the way.. building building the proyect not working in Fedora 29 and nvm:


gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/mdiazm/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.18.17-300.fc29.x86_64
gyp ERR! command \"/home/mdiazm/.nvm/versions/node/v8.11.2/bin/node\" \"/home/mdiazm/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /home/mdiazm/postbird/node_modules/libpq
gyp ERR! node -v v8.11.2
✨  Done in 9.49s.

**Comment by Paxa** [comment]
Libpq is an optional dependency, should work without it.
Does it work?

Also to use libpq, need to rebuilt for electron using `npm run rebuild_ext`

**Comment by Paxa** [comment]
Almost done https://github.com/Paxa/postbird/pull/41
