### ISSUE TITLE
Add custom snippets

### ISSUE THREAD

**Issue by hemip** [Paxa/postbird#38]
Have browsed through available information, but haven't found any info about possibilities to extend the list snippets with custom code. Is it possible without changing and recompiling the source code?

Best regards,
Hans

**Comment by Paxa** [comment]
That's gonna be useful, will try to make it in next release.
Do you have any suggestions for useful sql snippets?

**Comment by willvincent** [comment]
Would probably be useful to be able to manually add any the user sees fit, or perhaps a "Save as a snippet" from the query window.

The snippet window desperately needs a scrollbar too, for example the partitioning snippet is _far_ to large to be fully viewable, and as the container isn't scrollable it's impossible to access the full thing.

**Comment by hemip** [comment]
I like many of the included snippets, but I was looking for a simple way to do specific tasks like refreshing materialized views, running some house keeping tasks etc. Things that most likely are too specific for other users.
