### ISSUE TITLE
Edit column to numeric looses scale

### ISSUE THREAD

**Issue by Maxximus007** [Paxa/postbird#47]
Hi, like your tool! 

Seems that there is an issue with column edit. 

Changing a column to numeric and using the 'max length' field to add the precision and scale like 7,2 alters the column to numeric(7,0).

The generated query was: ALTER TABLE "public"."booking" ALTER COLUMN "total" TYPE numeric(7) USING "total"::numeric;

Probably due to field sanitizing?

**Comment by Paxa** [comment]
Fixed in master
