### ISSUE TITLE
TypeError: Invalid version 11.2 

### ISSUE THREAD

**Issue by Mintonne** [Paxa/postbird#50]
Hey,

I am getting this error when trying to connect to PostgreSQL Version 11.2 on Windows 10 1809.

![image](https://user-images.githubusercontent.com/39894801/53286568-a112c880-3768-11e9-9fe4-1604b19e6088.png)

I couldn't find any mention of a maximum allowed version so I am assuming this is a bug.

**Comment by Paxa** [comment]
That's a bug, already fixed in master.
Postgres don't include minor version (expected `11.2.0` but got `11.2`)

Will let you know when new version is released
