### ISSUE TITLE
Incorrect values with duplicate column names

### ISSUE THREAD

**Issue by pauldraper** [Paxa/postbird#51]
```sql
SELECT 1 a, 2 a
```

produces

| a | a |
|---|---|
| 2 | 2 |

It should be

| a | a |
|---|---|
| 1 | 2 |

**Comment by Paxa** [comment]
That's a bug, thanks for reporting.
Just curious, what is your use-case for duplicate column names?

**Comment by Paxa** [comment]
Fixed by https://github.com/Paxa/postbird/commit/6894e740a1f057c6cd536522ca8edd3152dbddcc
