### ISSUE TITLE
GUI without an exit function?

### ISSUE THREAD

**Issue by tempest766** [Paxa/postbird#53]
no exit command in the GUI?

**Comment by Paxa** [comment]
What platform do you use? mac or windows or linux?

**Comment by tempest766** [comment]
linux...Don't you think that any GUI application should have at least
have a file->quit pulldown on the menu bar, and preferably an
accelerator attached to the quit function?

**Comment by Paxa** [comment]
Will make it

**Comment by Paxa** [comment]
Fixed by https://github.com/Paxa/postbird/commit/41521d36f6c3e4a13094863555ecca2fd3bca704
