### ISSUE TITLE
Save as CSV doesn't work in version 0.8.2

### ISSUE THREAD

**Issue by lynxeyedua** [Paxa/postbird#56]
"Save as CSV" saves files with empty values divided by comma.
In the previous version(0.8.1), everything worked well.

OS: macOS Mojave 10.14.4

**Comment by Paxa** [comment]
same for me, will fix

**Comment by Paxa** [comment]
Fixed in master, new package https://postbird.paxa.kuber.host/2019_05_13.08_50-master-264d63c

**Comment by lynxeyedua** [comment]
It works, thank you!
