### ISSUE TITLE
Packaged .dmg does not work on OS X 10.14.5

### ISSUE THREAD

**Issue by seanfcarroll** [Paxa/postbird#61]
Running OS X 10.14.5, tried to install the .dmg from the GitHub project home page.

<img width="392" alt="Screenshot 2019-06-04 at 11 48 07" src="https://user-images.githubusercontent.com/11340230/58869548-c5166c00-86be-11e9-88a3-8f7d902ff5fe.png">

**Comment by Paxa** [comment]
Just tried again and I can open it. OS X 10.14.4
Did you complete downloads, your file is 59.4mb?

you may try latest master build from here https://postbird.paxa.kuber.host/2019_05_30.17_29-master-b6039f3

**Comment by rdp** [comment]
https://github.com/Paxa/postbird/releases/download/0.8.2/Postbird-0.8.2.dmg opens fine here 10.14.5 FWIW
