### ISSUE TITLE
Import SQL. What does it do?

### ISSUE THREAD

**Issue by mskogly** [Paxa/postbird#71]
New to postbird. installed and used the File > Import SQL to try to import a little snippet document  with a handful of commented out queries that I run often. But after import i seems to have dissapeared. Couldnt find any info on this feature, I forgive me for adding this as an issue. But what happens when using Import SQL?

**Comment by Paxa** [comment]
It will run that queries. (internally use `psql`)
Useful when creating database dump and import in other server

In your case probably you can copy all file content to query editor, then select query that you need to run and press Cmd+R (or Ctrl+R on linux and window) or press "Run Selection" in UI

I will consider to add feature to open sql file in editor and may be add some description on what import does
