### ISSUE TITLE
Connect to database (snap version)

### ISSUE THREAD

**Issue by silv4b** [Paxa/postbird#83]
**ERROR**: The snap version of postbird does not connect to the database, showing the error **connect EACCES 127.0.0.1:5432 - Local (undefined: undefined)**.  

OS: Deepin 15.11 x86_64 
Model: 80YH Lenovo ideapad 320-15IKB 
Kernel: 4.15.0-30deepin-generic 
DE: Deepin 
WM: KWin 
Terminal: deepin-terminal 
CPU: Intel i7-7500U (4) @ 3.5GHz 
GPU: NVIDIA GeForce 940MX 
Memory: 2153MB / 7884MB  

![Captura de Tela_Área de Seleção_20190806232900](https://user-images.githubusercontent.com/17997794/62590214-fc152380-b8a1-11e9-819b-88a178138400.png)

**Comment by Paxa** [comment]
Can you try to use latest build from https://postbird.paxa.kuber.host/2019_11_13.14_38-master-3ccf8fa and then open `View - Toggle Developer Tools`, does it show any error details?

**Comment by Paxa** [comment]
Also try connecting with `psql -h 127.0.0.1`

**Comment by Paxa** [comment]
You may try to connect with new version via socket file

In host name enter `/tmp`

If issue still exists, please re-open issue
