### ISSUE TITLE
How to setup for Login with peer METHOD?

### ISSUE THREAD

**Issue by csanyipal** [Paxa/postbird#89]
On my Xubuntu operating system I just installed postgresql 10 and Postbird.

The postgresql server is started and I do followings:

```
pali@lapos:~$ sudo su - postgres
postgres@lapos:~$ psql
postgres=# create user pali with CREATEDB;
postgres=# \q

postgres@lapos:~$ logout

pali@lapos:~$ createdb BeveteleimKiadasaim;
pali@lapos:~$ psql -U pali BeveteleimKiadasaim
psql (10.10 (Ubuntu 10.10-0ubuntu0.18.04.1))
Type "help" for help.

BeveteleimKiadasaim=> 
```

Now I want to login to postgresql server to this 'BeveteleimKiadasaim' database from Postbird too, like this:

Host: localhost
Port: 5432
Username: pali
Password: what to use here? I nothing enter here.
Database: BeveteleimKiadasaim

When I click on 'Test Connection' button in Postbird GUI, I get this message:
Connection Error
password authentication failed for user "pali"

I have in the '/etc/postgresql/10/main/pg_hba.conf' file this line:
```
# Database administrative login by Unix domain socket
local   all             postgres                                peer
```

but I want not change it like this:
`local   all             postgres                                md5`

Still how can I use Postbird GUI to connect to this 'BeveteleimKiadasaim' database out there?

**Comment by csanyipal** [comment]
I just try out the following URL:
`socket=/var/run/postgresql`
and get the message:
password authentication failed for user "pali"

**Comment by csanyipal** [comment]
I just solved this issue with following steps:
`sudo su - postgres`
`psql` 
`alter user pali with password '***********************';`
I can now use Postbird to connect the 'pali' user with it's password to the Host 'localhost'.

**Comment by Paxa** [comment]
Added support for socket connection https://github.com/Paxa/postbird/commit/74d1b907ed11ed8553369d3dc4ca2807d7a9a64d
To use it we need to set `host = /tmp` (or whatever you have in `unix_socket_directories` setting)
