### ISSUE TITLE
Test Connection not functioning well

### ISSUE THREAD

**Issue by yoonwaiyan** [Paxa/postbird#9]
Used test connection but even I removed all input from the field it still prompted me "Successfully connected".

**Comment by Paxa** [comment]
Which field did you remove?

I try to remove all fields it still connects, but if I enter wrong data then it shows connection error.

For database Postbird with set `template1` if you leave it empty.

I use Postgres.app and and probably it will use current system user and `localhost` by default, and 5432 as default port. I think it's convinient

**Comment by yoonwaiyan** [comment]
Okay. I think it's good to have placeholder so that users know it's connecting to localhost with port 5432 by default. I'll create a PR on this.
