### ISSUE TITLE
Error: column "relhasoids" does not exist

### ISSUE THREAD

**Issue by Victor19Rodrigues** [Paxa/postbird#90]
I'm using postgres 12 and this is the error:

`Error:` column "relhasoids" does not exist
Query: SELECT relhasoids FROM pg_catalog.pg_class, pg_catalog.pg_namespace n
      WHERE n.oid = pg_class.relnamespace AND nspname = 'public' AND relname = 'users'`

![Screenshot from 2019-10-07 10-03-41](https://user-images.githubusercontent.com/20098968/66314709-ca90f680-e8ea-11e9-81ec-733841a8555e.png)

**Comment by augustorl** [comment]
Same here ;/

**Comment by dionisioviei** [comment]
Same here, apparently this error only happens on postgres 12, i've installed postgres 11 and worked fine

**Comment by ZerotimeGit** [comment]
same problem here

**Comment by ZerotimeGit** [comment]
the problem ins on postbird and not postgres

**Comment by MarcosWillianR** [comment]
Same here too

**Comment by danileao** [comment]
According postgres documentation, in version 12 the OID was removed and Postbird not was updated  with this feature still. So if you using Postbird, you can use just until postgres 11

**Comment by Paxa** [comment]
Will fix when I have time. PR are welcome btw

**Comment by Andersonfrfilho** [comment]
I'm having this problem

**Comment by mleonizio** [comment]
Hi!
Same here!

![image](https://user-images.githubusercontent.com/1195559/66727297-99498680-ee14-11e9-8eed-d00b53d56b0f.png)

**Comment by Paxa** [comment]
Fixed in master, before new release can download artefacts at https://postbird.paxa.kuber.host/2019_10_14.06_42-master-7a9e949 and https://postbird.paxa.kuber.host/2019_10_14.05_42-master-7a9e949 (windows)

**Comment by Andersonfrfilho** [comment]
it worked for me.
thk

**Comment by SidneiAli** [comment]
it worked for me too.
tks

**Comment by mleonizio** [comment]
Ow.. thanks

Its worked for me too!

**Comment by tassiorego** [comment]
Not worked for the macOs Catalina. Tried

![image](https://user-images.githubusercontent.com/16306897/67124370-c5745700-f1c8-11e9-8a9d-6b2a6097b78b.png)

**Comment by lucasgalone** [comment]
Also here ;/

**Comment by Paxa** [comment]
@tassiorego
That issue because app is not signed by developer certificate
For first time:
1. Open "Applications"
2. use right click on Postbird.app -> Open
<img width="537" alt="Screen Shot 2019-11-20 at 14 13 17" src="https://user-images.githubusercontent.com/26019/69213780-0e407680-0ba0-11ea-856d-e2bc710bed48.png">

**Comment by Paxa** [comment]
Issue with `relhasoids` fixed in new release, sorry for inconvenience
