### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by lyandeveloper** [Paxa/postbird#93]
Whenever I try to run, an error appears "A JavaScript Error Has Occurred in the Main Process"...

**Comment by Marcelovqvd** [comment]
That problem is also ocurring here...

**Comment by Paxa** [comment]
What postbird version do you use? OS? Postgres Version?
Can send screenshots?
Anything in dev tools? (View -> Toggle Developer Tools)

**Comment by Marcelovqvd** [comment]
I was using 0.8.2 but I deleted it and now I`m trying to install 0.8.3

**Comment by mustaffxx** [comment]
Same here.
Windows 10 PRO.
Postbird 0.8.3
Postgres 9.5.19
![postbirderror](https://user-images.githubusercontent.com/32800045/69159895-5f306c00-0ac7-11ea-9bac-9734c1f03dfa.PNG)

**Comment by arturock** [comment]
Same issue here, I'm on Debian Sid and when launching from terminal I get the following error:
```sh
 ~/app/postbird  /home/me/app/postbird/postbird                                                                   1 ↵  09:12:38
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: electron.systemPreferences.subscribeNotification is not a function
    at Object.<anonymous> (/home/arturo/app/postbird/resources/app.asar/main.js:25:28)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Object.<anonymous> (/home/arturo/app/postbird/resources/electron.asar/browser/init.js:181:12)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
```

Apparently `systemPreferences` is macOS-specific

**Comment by Paxa** [comment]
I pushed a fix. Can you try this packages https://postbird.paxa.kuber.host/2019_11_19.15_31-master-65852d9

**Comment by cmonacaps** [comment]
👍 fix worked for me (windows 10 using setup.exe)

**Comment by arturock** [comment]
Working on Linux too

**Comment by evansmwendwa** [comment]
Working on linux - deepin

**Comment by MaurizioRicci** [comment]
> Same here.
> Windows 10 PRO.
> Postbird 0.8.3
> Postgres 9.5.19
> ![postbirderror](https://user-images.githubusercontent.com/32800045/69159895-5f306c00-0ac7-11ea-9bac-9734c1f03dfa.PNG)
> 
> Edit: Postbird 0.8.2 opens normally.

This is the same i error i got from updating from 0.8.2 to 0.8.3. Reverting back to 0.8.2 works without any error.

**Comment by Marcelovqvd** [comment]
Fix worked for me on windows 10! Tks!

**Comment by lyandeveloper** [comment]
Fixed worked for me too on windows 10! Thanks bro!

**Comment by Paxa** [comment]
Pushed new version. Sorry for inconvenience
