### ISSUE TITLE
Heroku: Connection error

### ISSUE THREAD

**Issue by egallup02360** [Paxa/postbird#95]
Issue appears to exist in most recent version (0.8.4 on Windows 10). When attempting to connect to Heroku database I'm met with the following error.

![image](https://user-images.githubusercontent.com/41955146/69253305-6ec0bb00-0b82-11ea-873d-3fd42ea6c082.png)

I was able to connect to Heroku databases without issue before this most recent update.

Edit: Just confirmed, issue does not exist in 0.8.2 (0.8.3 fails to run on Windows 10 so cannot confirm there).

**Comment by stevennyman** [comment]
It might have something to do with Heroku requiring SSL for database connections. https://devcenter.heroku.com/articles/heroku-postgresql#external-connections-ingress

**Comment by ansarizafar** [comment]
I am getting the same error. Is there any solution available?

**Comment by geeknees** [comment]
Same here. Making pull request seems right solution, but..I'm not familiar with electron things.

I found that I can connect using `Connet URL` with `ssl=verify-full`. You can check database address with heroku config command. 

`postgres://<username>:<password>@<host>:<port>/<database>?ssl=verify-full`

I hope someone fix this issue.

**Comment by adsteel** [comment]
This is still an issue for me. Looks like there's a fix though, which is exciting. Any plans to ship it?

**Comment by stevennyman** [comment]
The latest development artifacts seem to have this problem fixed (https://postbird.paxa.kuber.host/2020_01_19.16_38-master-1020bfa - link from near the bottom of the readme).
